services:
  network-deploy-service:
    networks:
      - microservices

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      # Temos que sobrescrever a propriedade pois localhost nao funcionara
      # O optional foi removido pois a aplicacao tera que fazer uso do configserver
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
