spring:
  application:
    name: "configserver"
  profiles:
    # Native para configuracao local
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///home//diego//repos//java//microservices//configserver//src//main//resources//config"
        git:
          uri: "https://github.com/eazybytes/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  # Valores padroes de conexao com o rabbitmq
  # docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:4.0-management
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

# Pro bus refresh funcionar os endpoints do actuator precisam estar habilitados
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

# accounts-prod.yml no github esta encriptado
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071
